import type { Deck, DeckFormat } from "@/protocol/deck";
import type { EngineKind } from "@/protocol";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AccountAsset = { id: string, url: string, kind: AssetKind, byteSize: number, state: AssetState, createdAt: string, };

export type AccountAssetList = { assets: Array<AccountAsset>, usedBytes: number, quotaBytes: number, };

export type AccountDeckDetail = { deck: Deck, id: string, name: string, format?: DeckFormat, description?: string, visibility: string, currentVersionId: string, currentVersionNo: number, publicationCount: number, derivedFromPresetKey?: string, createdAt: string, updatedAt: string, };

export type AccountDeckList = { decks: Array<AccountDeckSummary>, };

export type AccountDeckSummary = { id: string, name: string, format?: DeckFormat, description?: string, visibility: string, currentVersionId: string, currentVersionNo: number, publicationCount: number, derivedFromPresetKey?: string, createdAt: string, updatedAt: string, };

export type AccountExport = { exportedAt: string, account: AccountExportProfile, identities: Array<AccountExportIdentity>, sessions: Array<AccountExportSession>, decks: Array<AccountExportDeck>, publications: Array<AccountExportPublication>, favorites: Array<AccountExportFavorite>, };

export type AccountExportDeck = { deletedAt?: string, versions: Array<DeckVersionDetail>, id: string, name: string, format?: DeckFormat, description?: string, visibility: string, currentVersionId: string, currentVersionNo: number, publicationCount: number, derivedFromPresetKey?: string, createdAt: string, updatedAt: string, };

export type AccountExportFavorite = { deckhubEntryId: string, slug: string, title: string, createdAt: string, };

export type AccountExportIdentity = { providerUserId: string, emailVerified: boolean, createdAt: string, provider: string, email?: string, };

export type AccountExportProfile = { username?: string, displayName?: string, email?: string, providerAvatarUrl?: string, updatedAt?: string, id: string, handle: string, handlePending: boolean, createdAt: string, avatarAssetId?: string, avatarUrl?: string, };

export type AccountExportPublication = { id: string, deckId: string, publishedVersionId: string, slug: string, title: string, summary?: string, status: string, publishedAt?: string, createdAt: string, playCount: number, winCount: number, };

export type AccountExportSession = { createdAt: string, expiresAt: string, };

export type AdminTopDeckSnapshotEntry = { deckhubEntryId: string, rank: number, score?: number, reason?: string, };

export type AdminTopDeckSnapshotRequest = { snapshotDate: string, entries: Array<AdminTopDeckSnapshotEntry>, };

export type AssetCapabilities = { maxAvatarBytes: number, maxPlaymatBytes: number, };

export type AssetKind = "avatar" | "playmat";

export type AssetState = "pending" | "active";

export type AssetUpload = { assetId: string, uploadUrl: string, publicUrl: string, headers: Record<string, string>, };

export type Capability = "assets";

export type CardCollection = { version?: number, cards: Array<CardCollectionEntry>, };

export type CardCollectionEntry = { cardKey: string, quantity: number, };

export type CardPrintingIdentifier = { name: string, setCode: string, collectorNumber: string, foil?: boolean, };

export type ChatReportMessage = { from: string, text: string, sentAtMs: number, roomId?: string, seal?: string, };

export type ChatReportReason = "harassment" | "hate" | "inappropriate_content" | "spam" | "other";

export type ChatReportRequest = { reportedUsername: string, seal?: string, reason: ChatReportReason, details?: string, roomId?: string, transcript: ChatReportTranscript, };

export type ChatReportTranscript = { general: Array<ChatReportMessage>, room: Array<ChatReportMessage>, };

export type CreateAccountDeckRequest = { deck: Deck, notes?: string, };

export type CreateAssetUploadRequest = { kind: AssetKind, byteSize: number, };

export type DeckHubEntryDetail = { deck: Deck, id: string, deckId: string, publishedVersionId: string, publishedVersionNo: number, slug: string, title: string, summary?: string, author?: string, sourceKind: string, presetKey?: string, format?: DeckFormat, commanders: Array<string>, colors: string, cardCount: number, coverCardId?: string, coverCardName?: string, coverImageUrl?: string, status: string, publishedAt: string, tags: Array<DeckHubTag>, favoriteCount: number, favorited: boolean, ownedByViewer: boolean, engines?: Array<EngineKind>, };

export type DeckHubEntryList = { entries: Array<DeckHubEntrySummary>, total: number, page: number, pageSize: number, };

export type DeckHubEntrySummary = { id: string, deckId: string, publishedVersionId: string, publishedVersionNo: number, slug: string, title: string, summary?: string, author?: string, sourceKind: string, presetKey?: string, format?: DeckFormat, commanders: Array<string>, colors: string, cardCount: number, coverCardId?: string, coverCardName?: string, coverImageUrl?: string, status: string, publishedAt: string, tags: Array<DeckHubTag>, favoriteCount: number, favorited: boolean, ownedByViewer: boolean, engines?: Array<EngineKind>, };

export type DeckHubFacet = { key: string, label: string, count: number, };

export type DeckHubFacets = { total: number, formats: Array<DeckHubFacet>, colors: Array<DeckHubFacet>, tags: Array<DeckHubFacet>, };

export type DeckHubTag = { id: string, name: string, slug: string, };

export type DeckPlayReportRequest = { reportId: string, deckhubEntryId: string, deckFingerprint: string, format?: DeckFormat, };

export type DeckVersionDetail = { deck: Deck, id: string, versionNo: number, notes?: string, published: boolean, createdAt: string, };

export type DeckVersionSummary = { id: string, versionNo: number, notes?: string, published: boolean, createdAt: string, };

export type FavoriteResponse = { favoriteCount: number, favorited: boolean, };

export type HubCapabilities = { accountDecks: boolean, tags: boolean, favorites: boolean, topDeckSnapshots: boolean, assets?: AssetCapabilities, };

export type MissingCapabilityError = { capability: Capability, };

export type PublishDeckHubEntryRequest = { deckId: string, publishedVersionId: string, title: string, summary?: string, tags: Array<string>, coverCardId?: string, coverCardName?: string, };

export type SaveDeckVersionRequest = { deck: Deck, expectedVersionNo: number, notes?: string, };

export type SetAccountAvatarRequest = { assetId?: string, };

export type TopDeckBucket = { key: string, label: string, scope: string, entryCount: number, };

export type TopDeckSnapshot = { bucket: TopDeckBucket, snapshotDate?: string, entries: Array<TopDeckSnapshotEntry>, };

export type TopDeckSnapshotEntry = { rank: number, score?: number, reason?: string, entry: DeckHubEntrySummary, };

export type UpdateDeckHubEntryRequest = { title: string, summary?: string, tags: Array<string>, coverCardId?: string, coverCardName?: string, };

export type VerifyCardPrintingsRequest = { identifiers: Array<CardPrintingIdentifier>, };

export type VerifyCardPrintingsResponse = { matched: Array<boolean>, };
