// Generated by tools/build-keyword-help-sources.py. Do not author reminder prose here.
// Exact reminder-parenthesis contents from printed cards in local MTGJSON.
// Missing keywords/locales intentionally have no sourced generic quotation.
export type KeywordHelpLocale = "en" | "zh-Hans" | "zh-Hant";
export interface KeywordHelpSource {
  set: string;
  collectorNumber: string;
  card: string;
  printedName: string;
  language: string;
  url: string;
  field: string;
}
export interface SourcedKeywordHelp {
  parameter?: string;
  text: string;
  source: KeywordHelpSource;
}
export const KEYWORD_HELP_SOURCES: Record<string, Partial<Record<KeywordHelpLocale, SourcedKeywordHelp>>> = {
  "lifelink": {
    "en": {
      "text": "Damage dealt by this creature also causes you to gain that much life.",
      "source": {
        "set": "M19",
        "collectorNumber": "10",
        "card": "Daybreak Chaplain",
        "printedName": "Daybreak Chaplain",
        "language": "English",
        "url": "https://scryfall.com/card/c2f461b1-c801-4f0c-8fd7-fe68b6078ac6",
        "field": "cards[].originalText"
      }
    },
    "zh-Hans": {
      "text": "此生物所造成的伤害会让你获得等量的生命。",
      "source": {
        "set": "M19",
        "collectorNumber": "10",
        "card": "Daybreak Chaplain",
        "printedName": "破晓教士",
        "language": "Chinese Simplified",
        "url": "https://scryfall.com/card/d67ee9fb-9936-498c-9906-fc0599e0376a",
        "field": "cards[].foreignData[].text"
      }
    },
    "zh-Hant": {
      "text": "此生物所造成的傷害會讓你獲得等量的生命。",
      "source": {
        "set": "M19",
        "collectorNumber": "10",
        "card": "Daybreak Chaplain",
        "printedName": "破曉教士",
        "language": "Chinese Traditional",
        "url": "https://scryfall.com/card/8500e46d-215c-4ec9-af16-9862d1e28681",
        "field": "cards[].foreignData[].text"
      }
    }
  },
  "vigilance": {
    "en": {
      "text": "Attacking doesn't cause this creature to tap.",
      "source": {
        "set": "M19",
        "collectorNumber": "12",
        "card": "Gallant Cavalry",
        "printedName": "Gallant Cavalry",
        "language": "English",
        "url": "https://scryfall.com/card/e388c433-3a37-45f6-825a-d13d2223b6f7",
        "field": "cards[].originalText"
      }
    },
    "zh-Hans": {
      "text": "此生物攻击时不需横置。",
      "source": {
        "set": "M19",
        "collectorNumber": "12",
        "card": "Gallant Cavalry",
        "printedName": "华铠骑兵",
        "language": "Chinese Simplified",
        "url": "https://scryfall.com/card/20014e0e-04dd-441a-b7a4-1ff4476884f8",
        "field": "cards[].foreignData[].text"
      }
    },
    "zh-Hant": {
      "text": "此生物攻擊時不需橫置。",
      "source": {
        "set": "M19",
        "collectorNumber": "12",
        "card": "Gallant Cavalry",
        "printedName": "華鎧騎兵",
        "language": "Chinese Traditional",
        "url": "https://scryfall.com/card/66e71ed1-bec9-4987-99d3-aee76e2dbc5c",
        "field": "cards[].foreignData[].text"
      }
    }
  },
  "defender": {
    "en": {
      "text": "This creature can't attack.",
      "source": {
        "set": "M19",
        "collectorNumber": "30",
        "card": "Novice Knight",
        "printedName": "Novice Knight",
        "language": "English",
        "url": "https://scryfall.com/card/00101358-0e89-4bd1-b1f2-e889645b616e",
        "field": "cards[].originalText"
      }
    },
    "zh-Hans": {
      "text": "此生物不能攻击。",
      "source": {
        "set": "M19",
        "collectorNumber": "30",
        "card": "Novice Knight",
        "printedName": "新手骑士",
        "language": "Chinese Simplified",
        "url": "https://scryfall.com/card/dec3ba8a-5d2a-4d14-8704-5ca54747ce0a",
        "field": "cards[].foreignData[].text"
      }
    },
    "zh-Hant": {
      "text": "此生物不能攻擊。",
      "source": {
        "set": "M19",
        "collectorNumber": "30",
        "card": "Novice Knight",
        "printedName": "新手騎士",
        "language": "Chinese Traditional",
        "url": "https://scryfall.com/card/f29d1968-b955-4989-baad-990067f519a0",
        "field": "cards[].foreignData[].text"
      }
    }
  },
  "flash": {
    "en": {
      "text": "You may cast this spell any time you could cast an instant.",
      "source": {
        "set": "M19",
        "collectorNumber": "100",
        "card": "Hired Blade",
        "printedName": "Hired Blade",
        "language": "English",
        "url": "https://scryfall.com/card/7624c9aa-2f47-4fcc-a9fe-cc843e8de053",
        "field": "cards[].originalText"
      }
    },
    "zh-Hans": {
      "text": "你可以于你能够施放瞬间的时机下施放此咒语。",
      "source": {
        "set": "M19",
        "collectorNumber": "100",
        "card": "Hired Blade",
        "printedName": "雇剑打手",
        "language": "Chinese Simplified",
        "url": "https://scryfall.com/card/a7389525-6ff4-41a3-b56c-710cfa75f8c5",
        "field": "cards[].foreignData[].text"
      }
    },
    "zh-Hant": {
      "text": "你可以於你能夠施放瞬間的時機下施放此咒語。",
      "source": {
        "set": "M19",
        "collectorNumber": "100",
        "card": "Hired Blade",
        "printedName": "雇劍打手",
        "language": "Chinese Traditional",
        "url": "https://scryfall.com/card/8a80a810-b6de-4333-ad33-b254232ca1b5",
        "field": "cards[].foreignData[].text"
      }
    }
  },
  "menace": {
    "en": {
      "text": "This creature can't be blocked except by two or more creatures.",
      "source": {
        "set": "M19",
        "collectorNumber": "123",
        "card": "Two-Headed Zombie",
        "printedName": "Two-Headed Zombie",
        "language": "English",
        "url": "https://scryfall.com/card/2cc5760e-8b27-4d37-9772-c9eda90b1d95",
        "field": "cards[].originalText"
      }
    },
    "zh-Hans": {
      "text": "此生物只能被两个或更多生物阻挡。",
      "source": {
        "set": "M19",
        "collectorNumber": "123",
        "card": "Two-Headed Zombie",
        "printedName": "双头灵俑",
        "language": "Chinese Simplified",
        "url": "https://scryfall.com/card/5fab9612-47b9-4a42-83cb-a90743ff652e",
        "field": "cards[].foreignData[].text"
      }
    },
    "zh-Hant": {
      "text": "此生物只能被兩個或更多生物阻擋。",
      "source": {
        "set": "M19",
        "collectorNumber": "123",
        "card": "Two-Headed Zombie",
        "printedName": "雙頭殭屍",
        "language": "Chinese Traditional",
        "url": "https://scryfall.com/card/dbd61113-a5b1-4a22-b890-f386b53d4c9f",
        "field": "cards[].foreignData[].text"
      }
    }
  },
  "trample": {
    "en": {
      "text": "This creature can deal excess combat damage to the player or planeswalker it's attacking.",
      "source": {
        "set": "M19",
        "collectorNumber": "146",
        "card": "Havoc Devils",
        "printedName": "Havoc Devils",
        "language": "English",
        "url": "https://scryfall.com/card/2f003678-0f17-4f1d-87d5-83613a82044b",
        "field": "cards[].originalText"
      }
    },
    "zh-Hans": {
      "text": "此生物造成之过量战斗伤害能对所攻击的牌手或鹏洛客造成之。",
      "source": {
        "set": "M19",
        "collectorNumber": "146",
        "card": "Havoc Devils",
        "printedName": "浩劫魔鬼",
        "language": "Chinese Simplified",
        "url": "https://scryfall.com/card/2bc6e3f6-78a4-4c19-8691-c1b11ecb3f28",
        "field": "cards[].foreignData[].text"
      }
    },
    "zh-Hant": {
      "text": "此生物造成之過量戰鬥傷害能對所攻擊的玩家或鵬洛客造成之。",
      "source": {
        "set": "M19",
        "collectorNumber": "146",
        "card": "Havoc Devils",
        "printedName": "浩劫魔鬼",
        "language": "Chinese Traditional",
        "url": "https://scryfall.com/card/275a5f9c-18c3-40e4-9919-aa15d05ff2a5",
        "field": "cards[].foreignData[].text"
      }
    }
  },
  "haste": {
    "en": {
      "text": "This creature can attack and {T} as soon as it comes under your control.",
      "source": {
        "set": "M19",
        "collectorNumber": "147",
        "card": "Hostile Minotaur",
        "printedName": "Hostile Minotaur",
        "language": "English",
        "url": "https://scryfall.com/card/ad6d0a11-3a9c-4de0-9a46-06d2b9356eb7",
        "field": "cards[].originalText"
      }
    },
    "zh-Hans": {
      "text": "此生物受你操控时便能攻击与{T}。",
      "source": {
        "set": "M19",
        "collectorNumber": "147",
        "card": "Hostile Minotaur",
        "printedName": "敌意牛头怪",
        "language": "Chinese Simplified",
        "url": "https://scryfall.com/card/500a9913-a4cf-4a9e-ae46-66fee173f1a7",
        "field": "cards[].foreignData[].text"
      }
    },
    "zh-Hant": {
      "text": "此生物受你操控時便能攻擊與{T}。",
      "source": {
        "set": "M19",
        "collectorNumber": "147",
        "card": "Hostile Minotaur",
        "printedName": "敵意牛頭怪",
        "language": "Chinese Traditional",
        "url": "https://scryfall.com/card/8065a391-78d5-4a17-99f3-d98fc0d1d773",
        "field": "cards[].foreignData[].text"
      }
    }
  },
  "deathtouch": {
    "en": {
      "text": "Any amount of damage this deals to a creature is enough to destroy it.",
      "source": {
        "set": "M19",
        "collectorNumber": "174",
        "card": "Daggerback Basilisk",
        "printedName": "Daggerback Basilisk",
        "language": "English",
        "url": "https://scryfall.com/card/7bc8325b-c7a8-49a5-8a54-a419800ffb93",
        "field": "cards[].originalText"
      }
    },
    "zh-Hans": {
      "text": "它对生物造成的任何数量伤害都足以消灭后者。",
      "source": {
        "set": "M19",
        "collectorNumber": "174",
        "card": "Daggerback Basilisk",
        "printedName": "匕背蜥怪",
        "language": "Chinese Simplified",
        "url": "https://scryfall.com/card/e58f4663-013c-4f91-bc2f-29e90162cbc4",
        "field": "cards[].foreignData[].text"
      }
    },
    "zh-Hant": {
      "text": "它對生物造成的任何數量傷害都足以消滅後者。",
      "source": {
        "set": "M19",
        "collectorNumber": "174",
        "card": "Daggerback Basilisk",
        "printedName": "匕背蜥怪",
        "language": "Chinese Traditional",
        "url": "https://scryfall.com/card/098360f1-6993-49d5-9deb-2df44e2ba025",
        "field": "cards[].foreignData[].text"
      }
    }
  },
  "reach": {
    "en": {
      "text": "This creature can block creatures with flying.",
      "source": {
        "set": "M19",
        "collectorNumber": "183",
        "card": "Giant Spider",
        "printedName": "Giant Spider",
        "language": "English",
        "url": "https://scryfall.com/card/80996b0d-cd44-445e-96de-677e0018255c",
        "field": "cards[].originalText"
      }
    },
    "zh-Hans": {
      "text": "此生物能阻挡具飞行异能的生物。",
      "source": {
        "set": "M19",
        "collectorNumber": "183",
        "card": "Giant Spider",
        "printedName": "巨型蜘蛛",
        "language": "Chinese Simplified",
        "url": "https://scryfall.com/card/67e9ac87-a058-4a55-b0fc-27d55350165c",
        "field": "cards[].foreignData[].text"
      }
    },
    "zh-Hant": {
      "text": "此生物能阻擋具飛行異能的生物。",
      "source": {
        "set": "M19",
        "collectorNumber": "183",
        "card": "Giant Spider",
        "printedName": "巨型蜘蛛",
        "language": "Chinese Traditional",
        "url": "https://scryfall.com/card/4ba2c9a5-a32f-4878-bf9e-0f77de8adf0f",
        "field": "cards[].foreignData[].text"
      }
    }
  },
  "hexproof": {
    "en": {
      "text": "This creature can't be the target of spells or abilities your opponents control.",
      "source": {
        "set": "M19",
        "collectorNumber": "207",
        "card": "Vine Mare",
        "printedName": "Vine Mare",
        "language": "English",
        "url": "https://scryfall.com/card/b9980835-cd32-4870-88df-c79cd5534968",
        "field": "cards[].originalText"
      }
    },
    "zh-Hans": {
      "text": "此生物不能成为由对手操控之咒语或异能的目标。",
      "source": {
        "set": "M19",
        "collectorNumber": "207",
        "card": "Vine Mare",
        "printedName": "藤蔓牝马",
        "language": "Chinese Simplified",
        "url": "https://scryfall.com/card/01231e87-5035-437b-97ad-a64cd1a65431",
        "field": "cards[].foreignData[].text"
      }
    },
    "zh-Hant": {
      "text": "此生物不能成為由對手操控之咒語或異能的目標。",
      "source": {
        "set": "M19",
        "collectorNumber": "207",
        "card": "Vine Mare",
        "printedName": "藤蔓牝馬",
        "language": "Chinese Traditional",
        "url": "https://scryfall.com/card/3fe970af-4acd-4fda-a840-bc736b44ce99",
        "field": "cards[].foreignData[].text"
      }
    }
  },
  "flying": {
    "en": {
      "text": "This creature can't be blocked except by creatures with flying or reach.",
      "source": {
        "set": "M19",
        "collectorNumber": "285",
        "card": "Silverbeak Griffin",
        "printedName": "Silverbeak Griffin",
        "language": "English",
        "url": "https://scryfall.com/card/36b4c374-42a4-4912-8a74-a11c3fa0e065",
        "field": "cards[].originalText"
      }
    },
    "zh-Hans": {
      "text": "此生物只能被具飞行或延势异能的生物阻挡。",
      "source": {
        "set": "M19",
        "collectorNumber": "285",
        "card": "Silverbeak Griffin",
        "printedName": "银嘴狮鹫",
        "language": "Chinese Simplified",
        "url": "https://scryfall.com/card/a567e8ff-825c-48e7-a869-ebe7ae97accb",
        "field": "cards[].foreignData[].text"
      }
    },
    "zh-Hant": {
      "text": "此生物只能被具飛行或延勢異能的生物阻擋。",
      "source": {
        "set": "M19",
        "collectorNumber": "285",
        "card": "Silverbeak Griffin",
        "printedName": "銀嘴獅鷲",
        "language": "Chinese Traditional",
        "url": "https://scryfall.com/card/349e7da1-d662-49d9-85e3-492a0f9e93b1",
        "field": "cards[].foreignData[].text"
      }
    }
  },
  "double strike": {
    "en": {
      "text": "This creature deals both first-strike and regular combat damage.",
      "source": {
        "set": "M20",
        "collectorNumber": "16",
        "card": "Fencing Ace",
        "printedName": "Fencing Ace",
        "language": "English",
        "url": "https://scryfall.com/card/53f54b57-9516-424a-86a3-54843efadb0c",
        "field": "cards[].originalText"
      }
    },
    "zh-Hans": {
      "text": "此生物能造成先攻伤害以及普通战斗伤害。",
      "source": {
        "set": "M20",
        "collectorNumber": "16",
        "card": "Fencing Ace",
        "printedName": "击剑高手",
        "language": "Chinese Simplified",
        "url": "https://scryfall.com/card/e9f67a69-946a-4e42-8d25-29f7bedd8708",
        "field": "cards[].foreignData[].text"
      }
    },
    "zh-Hant": {
      "text": "此生物能造成先攻傷害以及普通戰鬥傷害。",
      "source": {
        "set": "M20",
        "collectorNumber": "16",
        "card": "Fencing Ace",
        "printedName": "擊劍高手",
        "language": "Chinese Traditional",
        "url": "https://scryfall.com/card/5de2f7bd-ada8-4aeb-a064-59595584ce3d",
        "field": "cards[].foreignData[].text"
      }
    }
  },
  "first strike": {
    "en": {
      "text": "This creature deals combat damage before creatures without first strike.",
      "source": {
        "set": "M20",
        "collectorNumber": "221",
        "card": "Anvilwrought Raptor",
        "printedName": "Anvilwrought Raptor",
        "language": "English",
        "url": "https://scryfall.com/card/aa6d7bbe-0418-4a58-a97b-13b50eb0b642",
        "field": "cards[].originalText"
      }
    },
    "zh-Hans": {
      "text": "此生物会比不具先攻异能的生物提前造成战斗伤害。",
      "source": {
        "set": "M20",
        "collectorNumber": "221",
        "card": "Anvilwrought Raptor",
        "printedName": "锻砧猛禽",
        "language": "Chinese Simplified",
        "url": "https://scryfall.com/card/273a790d-8a93-48b6-9f6d-1481f4b5a849",
        "field": "cards[].foreignData[].text"
      }
    },
    "zh-Hant": {
      "text": "此生物會比不具先攻異能的生物提前造成戰鬥傷害。",
      "source": {
        "set": "M20",
        "collectorNumber": "221",
        "card": "Anvilwrought Raptor",
        "printedName": "鍛砧猛禽",
        "language": "Chinese Traditional",
        "url": "https://scryfall.com/card/c1268d2b-3cab-4713-8b1a-ce32ffecd3bb",
        "field": "cards[].foreignData[].text"
      }
    }
  },
  "intimidate": {
    "en": {
      "text": "This creature can't be blocked except by artifact creatures and/or creatures that share a color with it.",
      "source": {
        "set": "M15",
        "collectorNumber": "85",
        "card": "Accursed Spirit",
        "printedName": "Accursed Spirit",
        "language": "English",
        "url": "https://scryfall.com/card/2513fe72-4e20-49e6-9970-839f1c635792",
        "field": "cards[].originalText"
      }
    },
    "zh-Hans": {
      "text": "此生物只能被神器生物和／或与它有共通颜色的生物阻挡。",
      "source": {
        "set": "M15",
        "collectorNumber": "85",
        "card": "Accursed Spirit",
        "printedName": "厄运鬼魂",
        "language": "Chinese Simplified",
        "url": "https://scryfall.com/card/ff1638a8-8972-4953-9046-290e33cba1cc",
        "field": "cards[].foreignData[].text"
      }
    },
    "zh-Hant": {
      "text": "此生物只能被神器生物和／或與它有共通顏色的生物阻擋。",
      "source": {
        "set": "M15",
        "collectorNumber": "85",
        "card": "Accursed Spirit",
        "printedName": "厄運鬼魂",
        "language": "Chinese Traditional",
        "url": "https://scryfall.com/card/eb7dba26-9135-4b97-8acf-d150688d42a1",
        "field": "cards[].foreignData[].text"
      }
    }
  },
  "prowess": {
    "en": {
      "text": "Whenever you cast a noncreature spell, this creature gets +1/+1 until end of turn.",
      "source": {
        "set": "M21",
        "collectorNumber": "53",
        "card": "Jeskai Elder",
        "printedName": "Jeskai Elder",
        "language": "English",
        "url": "https://scryfall.com/card/a188164c-01fe-4980-83a5-91d14e218cf5",
        "field": "cards[].originalText"
      }
    },
    "zh-Hans": {
      "text": "每当你施放非生物咒语时，此生物得+1/+1直到回合结束。",
      "source": {
        "set": "M21",
        "collectorNumber": "53",
        "card": "Jeskai Elder",
        "printedName": "洁斯凯长老",
        "language": "Chinese Simplified",
        "url": "https://scryfall.com/card/e53916d1-86d1-4843-a8b1-02d7f0c6b444",
        "field": "cards[].foreignData[].text"
      }
    },
    "zh-Hant": {
      "text": "每當你施放非生物咒語時，此生物得+1/+1直到回合結束。",
      "source": {
        "set": "M21",
        "collectorNumber": "53",
        "card": "Jeskai Elder",
        "printedName": "潔斯凱長老",
        "language": "Chinese Traditional",
        "url": "https://scryfall.com/card/211e8f54-6e53-4a8b-9431-9c35744e2f53",
        "field": "cards[].foreignData[].text"
      }
    }
  },
  "exalted": {
    "en": {
      "text": "Whenever a creature you control attacks alone, that creature gets +1/+1 until end of turn.",
      "source": {
        "set": "M13",
        "collectorNumber": "4",
        "card": "Angelic Benediction",
        "printedName": "Angelic Benediction",
        "language": "English",
        "url": "https://scryfall.com/card/22125507-31e3-424c-9527-d994e4525d75",
        "field": "cards[].originalText"
      }
    },
    "zh-Hans": {
      "text": "每当一个由你操控的生物单独攻击时，该生物得+1/+1直到回合结束。",
      "source": {
        "set": "M13",
        "collectorNumber": "4",
        "card": "Angelic Benediction",
        "printedName": "天使祈福",
        "language": "Chinese Simplified",
        "url": "https://scryfall.com/card/77f30812-0658-406b-aabb-b3ae3ed1ef77",
        "field": "cards[].foreignData[].text"
      }
    },
    "zh-Hant": {
      "text": "每當一個由你操控的生物單獨攻擊時，該生物得+1/+1直到回合結束。",
      "source": {
        "set": "M13",
        "collectorNumber": "4",
        "card": "Angelic Benediction",
        "printedName": "天使祈福",
        "language": "Chinese Traditional",
        "url": "https://scryfall.com/card/65feb6d0-cb9b-4c82-ba5e-361d842f5885",
        "field": "cards[].foreignData[].text"
      }
    }
  },
  "shroud": {
    "en": {
      "text": "This creature can't be the target of spells or abilities.",
      "source": {
        "set": "M10",
        "collectorNumber": "188",
        "card": "Kalonian Behemoth",
        "printedName": "Kalonian Behemoth",
        "language": "English",
        "url": "https://scryfall.com/card/77064471-d0c1-4988-8c47-f767bf9635f3",
        "field": "cards[].originalText"
      }
    },
    "zh-Hans": {
      "text": "此生物不能成为咒语或异能的目标。",
      "source": {
        "set": "M10",
        "collectorNumber": "188",
        "card": "Kalonian Behemoth",
        "printedName": "卡隆尼亚贝西摩斯",
        "language": "Chinese Simplified",
        "url": "https://scryfall.com/card/f1a75994-c832-4889-87cb-56174d04eef5",
        "field": "cards[].foreignData[].text"
      }
    },
    "zh-Hant": {
      "text": "此生物不能成為咒語或異能的目標。",
      "source": {
        "set": "CMR",
        "collectorNumber": "452",
        "card": "Simic Sky Swallower",
        "printedName": "析米克蔽空霸",
        "language": "Chinese Traditional",
        "url": "https://scryfall.com/card/f5487221-11f2-48f7-9a16-91e76dccc457",
        "field": "cards[].foreignData[].text"
      }
    }
  },
  "fear": {
    "en": {
      "text": "This creature can't be blocked except by artifact creatures and/or black creatures.",
      "source": {
        "set": "10E",
        "collectorNumber": "177",
        "card": "Severed Legion",
        "printedName": "Severed Legion",
        "language": "English",
        "url": "https://scryfall.com/card/82633f38-5af1-429e-8c9d-db536af85309",
        "field": "cards[].originalText"
      }
    },
    "zh-Hans": {
      "text": "此生物只能被神器生物和／或黑色生物阻挡。",
      "source": {
        "set": "A25",
        "collectorNumber": "99",
        "card": "Nezumi Cutthroat",
        "printedName": "割喉鼠人",
        "language": "Chinese Simplified",
        "url": "https://scryfall.com/card/870d206e-050a-43a2-9394-d8d0a53ea2a3",
        "field": "cards[].foreignData[].text"
      }
    },
    "zh-Hant": {
      "text": "此生物只能被神器生物和／或黑色生物阻擋。",
      "source": {
        "set": "AFC",
        "collectorNumber": "110",
        "card": "Shriekmaw",
        "printedName": "尖吼怪",
        "language": "Chinese Traditional",
        "url": "https://scryfall.com/card/deb12b85-b3ba-4a79-8bce-32c71bf99357",
        "field": "cards[].foreignData[].text"
      }
    }
  },
  "infect": {
    "en": {
      "text": "This creature deals damage to creatures in the form of -1/-1 counters and to players in the form of poison counters.",
      "source": {
        "set": "2XM",
        "collectorNumber": "107",
        "card": "Skithiryx, the Blight Dragon",
        "printedName": "Skithiryx, the Blight Dragon",
        "language": "English",
        "url": "https://scryfall.com/card/cab61c7e-e00a-413b-a0b5-7718b479582f",
        "field": "cards[].originalText"
      }
    },
    "zh-Hans": {
      "text": "此生物会以-1/-1指示物的方式对生物造成伤害，并以中毒指示物的方式对牌手造成伤害。",
      "source": {
        "set": "2XM",
        "collectorNumber": "107",
        "card": "Skithiryx, the Blight Dragon",
        "printedName": "枯萎巨龙极兹锐",
        "language": "Chinese Simplified",
        "url": "https://scryfall.com/card/c25d758c-3d22-4b49-ad5c-0f65e219ccac",
        "field": "cards[].foreignData[].text"
      }
    },
    "zh-Hant": {
      "text": "此生物會以-1/-1指示物的方式對生物造成傷害，並以中毒指示物的方式對玩家造成傷害。",
      "source": {
        "set": "MBS",
        "collectorNumber": "16",
        "card": "Priests of Norn",
        "printedName": "艾蕾儂僧侶",
        "language": "Chinese Traditional",
        "url": "https://scryfall.com/card/b620907c-523f-46d9-b120-ecd6689135f5",
        "field": "cards[].foreignData[].text"
      }
    }
  },
  "battle cry": {
    "en": {
      "text": "Whenever this creature attacks, each other attacking creature gets +1/+0 until end of turn.",
      "source": {
        "set": "40K",
        "collectorNumber": "137",
        "card": "Primaris Chaplain",
        "printedName": "Primaris Chaplain",
        "language": "English",
        "url": "https://scryfall.com/card/5b7cb578-968c-408b-b58a-8f38cfc7696b",
        "field": "cards[].originalText"
      }
    },
    "zh-Hans": {
      "text": "每当此生物攻击时，每个进行攻击的其他生物各得+1/+0直到回合结束。",
      "source": {
        "set": "40K",
        "collectorNumber": "137",
        "card": "Primaris Chaplain",
        "printedName": "原铸教士",
        "language": "Chinese Simplified",
        "url": "https://scryfall.com/card/41cec12b-d2fb-48e5-8b71-6a73fcb7772a",
        "field": "cards[].foreignData[].text"
      }
    },
    "zh-Hant": {
      "text": "每當此生物攻擊時，每個進行攻擊的其他生物各得+1/+0直到回合結束。",
      "source": {
        "set": "MBS",
        "collectorNumber": "1",
        "card": "Accorder Paladin",
        "printedName": "輪駐軍神聖武士",
        "language": "Chinese Traditional",
        "url": "https://scryfall.com/card/4da84c4f-4a49-4c71-a34c-e6f8662c4c8b",
        "field": "cards[].foreignData[].text"
      }
    }
  },
  "indestructible": {
    "en": {
      "text": "Damage and effects that say \"destroy\" don't destroy this creature. If its toughness is 0 or less, it's still put into its owner's graveyard.",
      "source": {
        "set": "AKH",
        "collectorNumber": "28",
        "card": "Seraph of the Suns",
        "printedName": "Seraph of the Suns",
        "language": "English",
        "url": "https://scryfall.com/card/85dc4ed8-4674-44a1-8a06-ecce72c85e60",
        "field": "cards[].originalText"
      }
    },
    "zh-Hans": {
      "text": "注明「消灭」的效应和伤害不会消灭此生物。如果其防御力降到0或更少，它仍会置入其拥有者的坟墓场。",
      "source": {
        "set": "AKH",
        "collectorNumber": "28",
        "card": "Seraph of the Suns",
        "printedName": "诸阳炽天使",
        "language": "Chinese Simplified",
        "url": "https://scryfall.com/card/3c31860f-de99-4450-b97d-894b808704b0",
        "field": "cards[].foreignData[].text"
      }
    },
    "zh-Hant": {
      "text": "註明「消滅」的效應和傷害不會消滅此生物。如果其防禦力降到0或更少，它仍會置入其擁有者的墳墓場。",
      "source": {
        "set": "AKH",
        "collectorNumber": "28",
        "card": "Seraph of the Suns",
        "printedName": "諸陽熾天使",
        "language": "Chinese Traditional",
        "url": "https://scryfall.com/card/f7330098-6849-472f-a183-652967184fd7",
        "field": "cards[].foreignData[].text"
      }
    }
  },
  "horsemanship": {
    "en": {
      "text": "This creature can't be blocked except by creatures with horsemanship.",
      "source": {
        "set": "C13",
        "collectorNumber": "49",
        "card": "Lu Xun, Scholar General",
        "printedName": "Lu Xun, Scholar General",
        "language": "English",
        "url": "https://scryfall.com/card/54274222-d2c3-4249-a12e-7a5f53331937",
        "field": "cards[].originalText"
      }
    },
    "zh-Hans": {
      "text": "此生物只能被具马术异能的生物阻挡。",
      "source": {
        "set": "MOC",
        "collectorNumber": "22",
        "card": "Herald of Hoofbeats",
        "printedName": "攒蹄传令使",
        "language": "Chinese Simplified",
        "url": "https://scryfall.com/card/ce65e739-b7b5-4f9c-b8e0-67e9b0c5475b",
        "field": "cards[].foreignData[].text"
      }
    }
  },
  "shadow": {
    "en": {
      "text": "This creature can block or be blocked by only creatures with shadow.",
      "source": {
        "set": "CLB",
        "collectorNumber": "748",
        "card": "Dauthi Horror",
        "printedName": "Dauthi Horror",
        "language": "English",
        "url": "https://scryfall.com/card/7c41afe6-7eed-4cf5-9bbb-ccc9f82cb4fa",
        "field": "cards[].originalText"
      }
    },
    "zh-Hans": {
      "text": "此生物只能阻挡具次元幽影异能的生物，亦只能被具此异能的生物阻挡。",
      "source": {
        "set": "CLB",
        "collectorNumber": "748",
        "card": "Dauthi Horror",
        "printedName": "道西惊惧兽",
        "language": "Chinese Simplified",
        "url": "https://scryfall.com/card/d36cacea-1ee2-4c04-884c-ee4a9a414091",
        "field": "cards[].foreignData[].text"
      }
    },
    "zh-Hant": {
      "text": "此生物只能阻擋具次元幽影異能的生物，亦只能被具此異能的生物阻擋。",
      "source": {
        "set": "CLB",
        "collectorNumber": "748",
        "card": "Dauthi Horror",
        "printedName": "道西驚懼獸",
        "language": "Chinese Traditional",
        "url": "https://scryfall.com/card/59a41a87-e5e0-4ce8-aa1c-a96b85712925",
        "field": "cards[].foreignData[].text"
      }
    }
  },
  "kicker": {
    "en": {
      "text": "You may pay an additional {1}{U} as you cast this spell.",
      "source": {
        "set": "DOM",
        "collectorNumber": "46",
        "card": "Blink of an Eye",
        "printedName": "Blink of an Eye",
        "language": "English",
        "url": "https://scryfall.com/card/ab830392-4d7e-4b45-93cf-35ed1e935228",
        "field": "cards[].originalText"
      },
      "parameter": "{1}{U}"
    },
    "zh-Hans": {
      "text": "你施放此咒语时可以额外支付{1}{U}。",
      "source": {
        "set": "DOM",
        "collectorNumber": "46",
        "card": "Blink of an Eye",
        "printedName": "眨眼即逝",
        "language": "Chinese Simplified",
        "url": "https://scryfall.com/card/737ea2a9-d78e-462c-ac67-f913a463f49c",
        "field": "cards[].foreignData[].text"
      },
      "parameter": "{1}{U}"
    },
    "zh-Hant": {
      "text": "你施放此咒語時可以額外支付{1}{U}。",
      "source": {
        "set": "DOM",
        "collectorNumber": "46",
        "card": "Blink of an Eye",
        "printedName": "眨眼即逝",
        "language": "Chinese Traditional",
        "url": "https://scryfall.com/card/38246898-3030-4618-9327-31742a276b80",
        "field": "cards[].foreignData[].text"
      },
      "parameter": "{1}{U}"
    }
  },
  "wither": {
    "en": {
      "text": "This deals damage to creatures in the form of -1/-1 counters.",
      "source": {
        "set": "EVE",
        "collectorNumber": "38",
        "card": "Necroskitter",
        "printedName": "Necroskitter",
        "language": "English",
        "url": "https://scryfall.com/card/02907b62-5456-4605-a8cd-321487928761",
        "field": "cards[].originalText"
      }
    },
    "zh-Hans": {
      "text": "此来源会以-1/-1指示物的方式对生物造成伤害。",
      "source": {
        "set": "EVE",
        "collectorNumber": "38",
        "card": "Necroskitter",
        "printedName": "掠行死灵",
        "language": "Chinese Simplified",
        "url": "https://scryfall.com/card/d65dab33-9934-4bda-9aa7-47843a8bf81d",
        "field": "cards[].foreignData[].text"
      }
    }
  },
  "decayed": {
    "zh-Hans": {
      "text": "具败朽异能的生物不能进行阻挡。当它攻击，在战斗结束时将它牺牲。",
      "source": {
        "set": "MID",
        "collectorNumber": "96",
        "card": "Diregraf Horde",
        "printedName": "战墓大群",
        "language": "Chinese Simplified",
        "url": "https://scryfall.com/card/fd2f2673-c44a-4108-b7ae-9c51a8a8698e",
        "field": "cards[].foreignData[].text"
      }
    },
    "zh-Hant": {
      "text": "具敗朽異能的生物不能進行阻擋。當它攻擊，在戰鬥結束時將它犧牲。",
      "source": {
        "set": "MID",
        "collectorNumber": "96",
        "card": "Diregraf Horde",
        "printedName": "戰墓大群",
        "language": "Chinese Traditional",
        "url": "https://scryfall.com/card/3a7e20e0-4591-4c7a-a3ec-3273c591b742",
        "field": "cards[].foreignData[].text"
      }
    },
    "en": {
      "text": "This creature can't block. When it attacks, sacrifice it at end of combat.",
      "source": {
        "set": "TDM",
        "collectorNumber": "87",
        "card": "Rot-Curse Rakshasa",
        "printedName": "Rot-Curse Rakshasa",
        "language": "English",
        "url": "https://scryfall.com/card/31276460-fa9d-47da-85c5-c4baa8074d0d",
        "field": "cards[].originalText"
      }
    }
  },
  "skulk": {
    "en": {
      "text": "This creature can't be blocked by creatures with greater power.",
      "source": {
        "set": "SOI",
        "collectorNumber": "63",
        "card": "Forgotten Creation",
        "printedName": "Forgotten Creation",
        "language": "English",
        "url": "https://scryfall.com/card/27f82ee6-b8cd-4dce-b213-3910302f30e9",
        "field": "cards[].originalText"
      }
    },
    "zh-Hans": {
      "text": "此生物不能被力量比它大的生物阻挡。",
      "source": {
        "set": "SOI",
        "collectorNumber": "63",
        "card": "Forgotten Creation",
        "printedName": "遭忘造物",
        "language": "Chinese Simplified",
        "url": "https://scryfall.com/card/374dcbd0-6883-4726-9438-ebf7947fdef2",
        "field": "cards[].foreignData[].text"
      }
    },
    "zh-Hant": {
      "text": "此生物不能被力量比它大的生物阻擋。",
      "source": {
        "set": "SOI",
        "collectorNumber": "63",
        "card": "Forgotten Creation",
        "printedName": "遭忘造物",
        "language": "Chinese Traditional",
        "url": "https://scryfall.com/card/29f2cc61-ddf9-4f36-ab7d-89c30fd0e63d",
        "field": "cards[].foreignData[].text"
      }
    }
  }
};
