// AUTO-GENERATED by `cargo run -p manabrew-relay-protocol --bin gen-protocol`. Do not edit.
import type { CardDto } from "../game";
import type { PromptInput } from "../prompts";

export interface PromptRequestEnvelope {
  promptId?: string;
  decidingPlayerId?: string;
  sourceCard?: CardDto;
  sourceAbilityText?: string;
}

export type PromptRequest<TInput extends { type: string }> = PromptRequestEnvelope & {
  input: TInput;
};

type DistributeRequest<TInput extends { type: string }> = TInput extends unknown
  ? PromptRequest<TInput>
  : never;

export type Prompt = DistributeRequest<PromptInput>;
