// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardDto } from "../game/index";
import type { GameViewDto } from "../game/index";
import type { PromptInput } from "../prompts/promptInput";
import type { PromptOutput } from "../prompts/promptOutput";

export type AgentPrompt = { promptId: number, decidingPlayerId: string, sourceCard?: CardDto, sourceAbilityText?: string, input: PromptInput, };

export type ClientToServerMessage = { "kind": "response", promptId: number, action: PromptOutput, } | { "kind": "directive", directive: DirectiveInput, };

export type DirectiveInput = { "type": "concede" };

export type ProtocolError = { code: ProtocolErrorCode, message: string, promptId?: number, };

export type ProtocolErrorCode = "stalePrompt" | "wrongPlayer" | "wrongPromptType" | "unknownActionId" | "cancelNotAllowed" | "invalidShape";

export type StateUpdate = { gameView: GameViewDto, };
