// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PromptPresentation } from "./common";

export type ChooseColorInput = { presentation: PromptPresentation, validColors: Array<string>, amount: number, repeatAllowed: boolean, };

export type ChooseColorOutput = { "type": "colorDecision", chosenColors: { [key in string]?: number }, };
