// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Mana } from "../game/index";
import type { TargetingIntent } from "../game/index";

export type ActivatableAbilityInfo = { cardId: string, abilityIndex: number, description: string, isManaAbility: boolean, isClassLevelUp?: boolean, cost?: string, producedMana?: Array<Mana>, };

/**
 * Mirrors the engine's `AlternativeCost` (itself a mirror of Java's).
 */
export type AlternativeCostKind = "flashback" | "spectacle" | "evoke" | "dash" | "blitz" | "escape" | "overload" | "madness" | "foretell" | "emerge" | "suspend" | "morph" | "megamorph" | "bestow" | "warp" | "sacrificeAlt" | "plot" | "awaken" | "disturb" | "harmonize" | "freerunning" | "impending" | "mayhem" | "moreThanMeetsTheEye" | "mutate" | "prowl" | "sneak" | "surge" | "webSlinging" | "plotted";

export type AttackAssignment = { attackerId: string, targetId: string, };

export type AttackTargetDto = { id: string, label: string, kind: AttackTargetKind, };

export type AttackTargetKind = "player" | "planeswalker" | "battle";

export type AvailableAction = { id: string, } & ({ "type": "cast", cardId: string, mode: PlayCardMode, label: string, } | { "type": "activateAbility" } & ActivatableAbilityInfo | { "type": "undoMana", cardId: string, });

export type BlockAssignment = { blockerId: string, attackerId: string, };

export type CombatDamageAssignmentEntry = { assigneeId: string, damage: number, };

export type PaymentAction = { id: string, } & ({ "type": "activateManaAbility" } & ActivatableAbilityInfo | { "type": "undoMana", cardId: string, } | { "type": "useResource", cardId: string, resource: PaymentResourceKind, } | { "type": "releaseResource", cardId: string, resource: PaymentResourceKind, } | { "type": "payLife", amount: number, });

export type PaymentResourceKind = "convoke" | "improvise" | "delve" | "waterbend";

/**
 * Mirrors the engine's `PlayCardMode`.
 */
export type PlayCardMode = { "type": "normal" } | { "type": "backFaceLand" } | { "type": "roomRightSplit" } | { "type": "alternative", cost: AlternativeCostKind, } | { "type": "staticAlternative" } | { "type": "foretellExile" } | { "type": "unlockDoor" };

export type PromptPresentation = { title: string, description?: string, text?: string, targets: Array<TargetRef>, };

export type TargetKind = "player" | "card" | "spell";

export type TargetRef = { kind: TargetKind, id: string, intent?: TargetingIntent, oracle?: string, };
