// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PromptPresentation } from "./common";

export type DiceRollEntry = { label?: string, playerId?: string, round: number, naturalResults: Array<number>, finalResults: Array<number>, ignoredRolls: Array<number>, highlighted: boolean, };

export type DiceRolledInput = { presentation: PromptPresentation, sides: number, rolls: Array<DiceRollEntry>, };

export type DiceRolledOutput = { "type": "diceRolledAcknowledged" };
