// AUTO-GENERATED by `cargo run -p manabrew-relay-protocol --bin gen-protocol`. Do not edit.
export * from "./chooseAction";
export * from "./chooseAttackers";
export * from "./chooseBlockers";
export * from "./chooseBoardTargets";
export * from "./chooseBoolean";
export * from "./chooseCards";
export * from "./chooseColor";
export * from "./chooseCombatDamageAssignment";
export * from "./chooseDamageAssignmentOrder";
export * from "./chooseFromSelection";
export * from "./chooseNumber";
export * from "./common";
export * from "./diceRolled";
export * from "./gameOver";
export * from "./mulligan";
export * from "./mulliganPutBack";
export * from "./payManaCost";
export * from "./promptInput";
export * from "./promptOutput";
export * from "./reorder";
export * from "./reveal";
export * from "./scry";

import type { PromptInput } from "./promptInput";
export type PromptType = PromptInput["type"];
