// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaymentAction } from "./common";
import type { PromptPresentation } from "./common";

export type PayManaCostInput = { presentation: PromptPresentation, cardId: string, cardName: string, manaCost: string, canConfirmFromPool: boolean, actions: Array<PaymentAction>, };

export type PayManaCostOutput = { "type": "act", actionId: string, } | { "type": "pay", auto: boolean, } | { "type": "cancel" };
