// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChooseActionInput } from "./chooseAction";
import type { ChooseAttackersInput } from "./chooseAttackers";
import type { ChooseBlockersInput } from "./chooseBlockers";
import type { ChooseBoardTargetsInput } from "./chooseBoardTargets";
import type { ChooseBooleanInput } from "./chooseBoolean";
import type { ChooseCardsInput } from "./chooseCards";
import type { ChooseColorInput } from "./chooseColor";
import type { ChooseCombatDamageAssignmentInput } from "./chooseCombatDamageAssignment";
import type { ChooseDamageAssignmentOrderInput } from "./chooseDamageAssignmentOrder";
import type { ChooseFromSelectionInput } from "./chooseFromSelection";
import type { ChooseNumberInput } from "./chooseNumber";
import type { DiceRolledInput } from "./diceRolled";
import type { GameOverInput } from "./gameOver";
import type { MulliganInput } from "./mulligan";
import type { MulliganPutBackInput } from "./mulliganPutBack";
import type { PayManaCostInput } from "./payManaCost";
import type { ReorderInput } from "./reorder";
import type { RevealCardsInput } from "./reveal";
import type { ScryInput } from "./scry";

import type { SideboardInput } from "./sideboard";
export type PromptInput = { type: "sideboard" } & SideboardInput | { "type": "mulligan" } & MulliganInput | { "type": "mulliganPutBack" } & MulliganPutBackInput | { "type": "chooseAction" } & ChooseActionInput | { "type": "chooseAttackers" } & ChooseAttackersInput | { "type": "chooseBlockers" } & ChooseBlockersInput | { "type": "chooseBoardTargets" } & ChooseBoardTargetsInput | { "type": "chooseBoolean" } & ChooseBooleanInput | { "type": "chooseFromSelection" } & ChooseFromSelectionInput | { "type": "gameOver" } & GameOverInput | { "type": "revealCards" } & RevealCardsInput | { "type": "scry" } & ScryInput | { "type": "chooseColor" } & ChooseColorInput | { "type": "chooseNumber" } & ChooseNumberInput | { "type": "chooseDamageAssignmentOrder" } & ChooseDamageAssignmentOrderInput | { "type": "chooseCombatDamageAssignment" } & ChooseCombatDamageAssignmentInput | { "type": "payManaCost" } & PayManaCostInput | { "type": "chooseCards" } & ChooseCardsInput | { "type": "reorder" } & ReorderInput | { "type": "diceRolled" } & DiceRolledInput;
