// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardDto } from "../game/index";
import type { PromptPresentation } from "./common";

export type ReorderInput = { presentation: PromptPresentation, items: Array<ReorderItem>, };

export type ReorderItem = { id: string, card: CardDto, oracle?: string, };

export type ReorderOutput = { "type": "reorderDecision", orderedIds: Array<string>, };
