// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardDto } from "../game/index";
import type { PromptPresentation } from "./common";
import type { ZoneKind } from "../game/index";

export type RevealCardsInput = { presentation: PromptPresentation, cards: Array<CardDto>, zone: ZoneKind, ownerPlayerId: string, };

export type RevealCardsOutput = { "type": "revealCardsAcknowledged" };
