// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TargetRef } from "../prompts/common";
import type { TokenScript } from "../token";

export type CardChoiceDto = { "kind": "color", colors: Array<ManaColor>, } | { "kind": "type", values: Array<string>, } | { "kind": "namedCard", names: Array<string>, } | { "kind": "chosenCard", count: number, } | { "kind": "number", value: number, } | { "kind": "mode", value: string, } | { "kind": "player", playerId: string, name: string, };

export type CardDto = { id: string, identity: CardIdentity, color: string, manaCost: string, cmc: number, types: Array<string>, subtypes: Array<string>, supertypes: Array<string>, power: string | null, toughness: string | null, basePower?: number, baseToughness?: number, finalChapter?: number, classLevel?: number, classLevels: Array<ClassLevelDto>, sagaChapters: Array<SagaChapterDto>, text: string, choices: Array<CardChoiceDto>, controllerId: string, ownerId: string, tapped: boolean, isCrewed: boolean, isAttacking: boolean, attackingPlayerId?: string, attackTargetId?: string, keywords: Array<string>, counters: Record<string, number>, damage: number, summoningSick: boolean, isCopy: boolean, isDoubleFaced: boolean, isTransformed: boolean, isFaceDown: boolean, isBestowed: boolean, phasedOut: boolean, exerted: boolean, isRingBearer: boolean, attachedTo?: string, attachmentIds: Array<string>, mergedCardIds: Array<string>, flashbackCost?: string, kickerCost?: string, effectiveManaCost?: string, commanderTax?: number, madnessCost?: string, isMadnessExiled: boolean, isPlotted: boolean, isWarpExiled: boolean, foil: boolean, wouldDieInCombat: boolean, };

export type CardIdentity = { name: string, setCode: string, cardNumber: string, isToken: boolean, tokenScript?: TokenScript, };

export type CardView = { "visibility": "visible" } & CardDto | { "visibility": "hidden", id: string, };

export type ClassLevelDto = { level: number, oracle: string, cost?: string, };

export type CombatAssignmentDto = { blockerId: string, attackerId: string, };

export type DayTime = "neither" | "day" | "night";

export type DungeonStateDto = { name: string, room: string, };

export type EngineKind = "Manabrew" | "Forge" | "Ironsmith";

export type GameFormat = "Any" | "Standard" | "Pioneer" | "Modern" | "Legacy" | "Vintage" | "Pauper" | "Premodern" | "Commander" | "Brawl" | "Oathbreaker" | "Draft" | "Sealed";

export type GameViewDto = { gameId: string, turn: number, step: StepKind, combatAssignments: Array<CombatAssignmentDto>, activePlayerId: string, priorityPlayerId: string, players: Array<PlayerDto>, zones: Array<ZoneDto>, stack: Array<StackObjectDto>, gameOver: boolean, winnerId: string | null, monarchId: string | null, initiativeHolderId: string | null, dayTime: DayTime, activePlaneNames?: Array<string>, };

export type Mana = { color: ManaColor, amount: number, };

export type ManaColor = "W" | "U" | "B" | "R" | "G" | "C";

export type PlayerCounterKind = "poison" | "energy" | "experience" | "radiation" | "ticket";

export type PlayerDto = { id: string, name: string, status: PlayerStatus, isHuman: boolean, life: number, maxHandSize: number, unlimitedHandSize: boolean, landsPlayedThisTurn: number, maxLandPlaysPerTurn: number, unlimitedLandPlays: boolean, cardsDrawnThisTurn: number, damagePrevention: number, isExtraTurn: boolean, extraTurnCount: number, controlledBy?: string, playerKeywords: Array<string>, commanderCasts: Record<string, number>, dungeonState?: DungeonStateDto, activeSchemeNames?: Array<string>, teamNumber?: number, counters: { [key in PlayerCounterKind]?: number }, manaPool: { [key in ManaColor]?: number }, commanderDamage: Record<string, number>, hasCityBlessing: boolean, hasEnduringStory: boolean, ringLevel: number, speed: number, };

export type PlayerStatus = "playing" | "lost" | "conceded";

export type PlaymatSettings = { opacity?: number, texture?: number, borderWidth?: number, borderColor?: string, fit?: string, offsetX?: number, offsetY?: number, zoom?: number, blur?: number, brightness?: number, color?: string, };

export type SagaChapterDto = { chapters: Array<number>, oracle: string, };

export type StackObjectDto = { id: string, sourceId: string, controllerId: string, ownerId: string, identity: CardIdentity, text: string, sourceAbilityText?: string, isPermanentSpell: boolean, isCasting: boolean, isDoubleFaced: boolean, faceIndex: number, targets: Array<TargetRef>, };

export type StepKind = "untap" | "upkeep" | "draw" | "main1" | "combatBegin" | "combatDeclareAttackers" | "combatDeclareBlockers" | "combatFirstStrikeDamage" | "combatDamage" | "combatEnd" | "main2" | "endOfTurn" | "cleanup";

export type TargetingIntent = "damage" | "destroy" | "sacrifice" | "exile" | "bounce" | "mill" | "discard" | "counter" | "tap" | "untap" | "copy" | "buff" | "debuff" | "heal" | "loseLife" | "reveal" | "draw" | "fetch" | "gainControl" | "fight" | "attach" | "attack" | "block" | "hostile" | "friendly";

export type ZoneDto = { zone: ZoneKind, ownerId: string, cards: Array<CardView>, count: number, };

export type ZoneKind = "battlefield" | "hand" | "library" | "graveyard" | "exile" | "command";
