// AUTO-GENERATED by `cargo run -p manabrew-relay-protocol --bin gen-protocol`. Do not edit.
export const VERSION = "5.11.1";
export const RELAY_PROTOCOL_VERSION = "5.14.2";
export const PROTOCOL_VERSION = 5;
